### ISSUE TITLE
path to a other file

### ISSUE THREAD

**Issue by MadKilzz** [serverwentdown/file-manager#5]
### Describe the problem

Where can i change the path what is open now its ./ but when i wil a other file.
 i know you say that i need to run de file manager in the folder but 
 i making a panel for a host and i wil add a file manager and i can not download de file manager in each file is there a other way?

### Steps to reproduce

1. checked the code

### Screenshots or logs
No screens needed

### What is my question?
is there a other way?

**Comment by serverwentdown** [comment]
Reopen if you need help
